### ISSUE TITLE
Checksum requirement?

### ISSUE THREAD

**Issue by yoitsro** [glycerine/grpc-demo#1]
Hey! Thanks for your example. Is a checksum required? I would have thought the network level encryption would be sufficient: https://groups.google.com/forum/#!topic/grpc-io/dfWEsglPy8k

**Comment by glycerine** [comment]
It's cheap insurance against bugs in the reassembly code, which caught several issues in my code the first time I worked with grpc. Static type checking at compile time isn't strictly necessary either, but both catch bugs earlier rather than later.  Obviously you can turn it off once you are convinced of correctness. But I prefer having a high level end-to-end correctness check myself.
